In [58]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, classification_report
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier

In [59]:
df=pd.read_excel(r"C:\Users\vasun\Downloads\Practice_data_with_pass_fail.xlsx")

In [60]:
df.duplicated().sum()

3

In [61]:
df=df.drop_duplicates()

In [62]:
df.duplicated().sum()

0

In [63]:
print(df["Attendance_Pct"].mean())
print(df["Attendance_Pct"].median())

81.0
81.5

In [64]:
df["Attendance_Pct"]=df["Attendance_Pct"].fillna(df["Attendance_Pct"].median())

In [65]:
print(round(df["Study_Hours_Per_Day"].mean(),1))
print(df["Study_Hours_Per_Day"].median())

6.3
6.35

In [66]:
df["Study_Hours_Per_Day"]=df["Study_Hours_Per_Day"].fillna(round(df["Study_Hours_Per_Day"].median(),1))

In [67]:
print(df["Internal_Marks"].mean())
print(df["Internal_Marks"].median())

69.125
69.0

In [68]:
df["Internal_Marks"]=df["Internal_Marks"].fillna(df["Internal_Marks"].median())

In [69]:
print(df["Assignments_Completed"].mean())
print(df["Assignments_Completed"].median())

7.791666666666667
8.0

In [70]:
df["Assignments_Completed"]=df["Assignments_Completed"].fillna(df["Assignments_Completed"].median())

In [71]:
df.isnull().sum()

Student_ID               0
Department               0
Gender                   0
Attendance_Pct           0
Study_Hours_Per_Day      0
Internal_Marks           0
Assignments_Completed    0
Final_Score              0
pass_fail                0
dtype: int64

In [72]:
X = df[
    [
        "Attendance_Pct",
        "Study_Hours_Per_Day",
        "Internal_Marks",
        "Assignments_Completed",
        "Final_Score"
    ]
]

y = df["pass_fail"]

In [73]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [74]:
X_train

,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score
22,94.0,9.2,89.0,10.0,96
5,95.0,9.0,88.0,10.0,94
2,76.0,5.5,61.0,7.0,70
12,74.0,5.0,63.0,7.0,69
15,78.0,5.8,69.0,7.0,72
3,88.0,7.0,79.0,9.0,84
4,72.0,4.0,58.0,6.0,64
20,83.0,6.8,71.0,8.0,80
17,86.0,7.2,73.0,8.0,82
21,71.0,4.8,59.0,6.0,66
18,65.0,3.0,49.0,5.0,55
24,73.0,4.2,57.0,6.0,63
7,84.0,6.5,70.0,8.0,77
10,69.0,4.5,55.0,6.0,62
14,81.0,6.3,72.0,8.0,79
19,89.0,7.5,81.0,9.0,86
6,67.0,3.5,52.0,5.0,59

In [75]:
y_train

22    Pass
5     Pass
2     Pass
12    Fail
15    Fail
3     Pass
4     Fail
20    Pass
17    Pass
21    Fail
18    Fail
24    Fail
7     Pass
10    Fail
14    Pass
19    Pass
6     Fail
Name: pass_fail, dtype: object

In [76]:
X_test

,Attendance_Pct,Study_Hours_Per_Day,Internal_Marks,Assignments_Completed,Final_Score
8,79.0,6.0,66.0,8.0,73
16,81.5,6.2,67.0,8.0,75
0,82.0,7.5,68.0,9.0,78
23,77.0,5.2,64.0,7.0,71
11,87.0,7.8,76.0,9.0,83
9,93.0,8.5,82.0,10.0,90
13,90.0,8.0,85.0,9.0,88
1,91.0,8.2,74.0,10.0,86

In [77]:
y_test

8     Pass
16    Pass
0     Pass
23    Pass
11    Pass
9     Pass
13    Pass
1     Pass
Name: pass_fail, dtype: object

In [78]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(max_depth=4, random_state=42),
    "Random Forest" : RandomForestClassifier(n_estimators=100, random_state=42)
}

In [79]:
for name,model in models.items():
    model.fit(X_train,y_train)
    predictions=model.predict(X_test)

    print(f"\n{name}")
    print(classification_report(y_test, predictions, zero_division=0))
    print(predictions)
    print(y_test)

Logistic Regression
              precision    recall  f1-score   support

        Pass       1.00      1.00      1.00         8

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8

['Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']
8     Pass
16    Pass
0     Pass
23    Pass
11    Pass
9     Pass
13    Pass
1     Pass
Name: pass_fail, dtype: object

Decision Tree
              precision    recall  f1-score   support

        Fail       0.00      0.00      0.00         0
        Pass       1.00      0.88      0.93         8

    accuracy                           0.88         8
   macro avg       0.50      0.44      0.47         8
weighted avg       1.00      0.88      0.93         8

['Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass']
8     Pass
16    Pass
0     Pass
23    Pass
11    Pass
9     Pass
13    Pass
1     Pass
Name: pass_fail, dtype: object

Random Forest
              precision    recall  f1-score   support

        Fail       0.00      0.00      0.00         0
        Pass       1.00      0.88      0.93         8

    accuracy                           0.88         8
   macro avg       0.50      0.44      0.47         8
weighted avg       1.00      0.88      0.93         8

['Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']
8     Pass
16    Pass
0     Pass
23    Pass
11    Pass
9     Pass
13    Pass
1     Pass
Name: pass_fail, dtype: object